'use strict';

/**
 * Perfil por defecto de ProgramBI
 * Cursos: Excel, Power BI, SQL Server, IA, Big Data, ML, Power Automate, Análisis de datos
 */
const KEYWORDS_DEFAULT = {
  umbral: 1,
  // true = exige al menos una keyword técnica (no solo "capacitación")
  requireTecnico: true,
  cursos: [
    {
      id: 'excel',
      nombre: 'Excel',
      keywords: [
        'excel',
        'microsoft excel',
        'vba',
        'macros',
        'hoja de calculo',
        'hojas de calculo',
        'planilla',
        'planillas',
        'power query',
        'power pivot',
        'tablas dinamicas',
      ],
    },
    {
      id: 'powerbi',
      nombre: 'Power BI',
      keywords: [
        'power bi',
        'powerbi',
        'power-bi',
        'microsoft power bi',
        'dax',
        'tablero de control',
        'tableros de control',
        'dashboard',
        'dashboards',
        'business intelligence',
        'inteligencia de negocios',
      ],
    },
    {
      id: 'sql',
      nombre: 'SQL Server',
      keywords: [
        'sql server',
        'microsoft sql',
        'tsql',
        't-sql',
        'transact-sql',
        'transact sql',
        'base de datos',
        'bases de datos',
        'stored procedure',
        'procedimientos almacenados',
        'ssis',
        'ssrs',
        'ssas',
      ],
    },
    {
      id: 'powerautomate',
      nombre: 'Power Automate',
      keywords: [
        'power automate',
        'powerautomate',
        'power apps',
        'powerapps',
        'power platform',
        'microsoft power platform',
        'flujos de trabajo',
        'automatizacion de procesos',
        'rpa',
        'robotic process',
      ],
    },
    {
      id: 'analisis',
      nombre: 'Análisis de datos',
      keywords: [
        'analisis de datos',
        'analitica de datos',
        'analitica',
        'data analytics',
        'visualizacion de datos',
        'visualizacion',
        'etl',
        'datamart',
        'data warehouse',
        'datawarehouse',
        'indicadores de gestion',
        'kpi',
        'reportes gerenciales',
      ],
    },
    {
      id: 'ia',
      nombre: 'IA / Machine Learning',
      keywords: [
        'inteligencia artificial',
        'machine learning',
        'aprendizaje automatico',
        'deep learning',
        'aprendizaje profundo',
        'ciencia de datos',
        'data science',
        'redes neuronales',
        'analisis predictivo',
        'modelos predictivos',
        'algoritmos de ia',
        'chatbot',
        'llm',
        'generative ai',
        'ia generativa',
      ],
    },
    {
      id: 'bigdata',
      nombre: 'Big Data',
      keywords: [
        'big data',
        'bigdata',
        'hadoop',
        'spark',
        'data lake',
        'datalake',
        'procesamiento de datos masivos',
        'datos masivos',
      ],
    },
    {
      id: 'python',
      nombre: 'Python / Programación',
      keywords: [
        'python',
        'programacion',
        'desarrollo de software',
        'lenguaje de programacion',
        'pandas',
        'django',
        'flask',
        'scripting',
      ],
    },
    {
      id: 'formacion',
      nombre: 'Capacitación / Formación',
      keywords: [
        'capacitacion',
        'capacitaciones',
        'formacion',
        'curso',
        'cursos',
        'taller',
        'talleres',
        'entrenamiento',
        'perfeccionamiento',
        'docencia',
        'capacitar',
        'instructoria',
        'diplomado',
        'certificacion',
        'e-learning',
        'elearning',
        'capacitacion online',
        'capacitacion presencial',
      ],
    },
  ],
};

module.exports = { KEYWORDS_DEFAULT };
