'use strict';

/**
 * Perfil por defecto de ProgramBI
 * Cursos: Excel, Power BI, SQL Server, IA, Big Data, ML, Power Automate, Análisis de datos
 */
const KEYWORDS_DEFAULT = {
  umbral: 1,
  // true = exige al menos una keyword técnica (no solo "capacitación")
  requireTecnico: true,
  cursos: [
    {
      id: 'excel',
      nombre: 'Excel',
      keywords: [
        'excel',
        'microsoft excel',
        'vba',
        'macro',
        'macros',
        'hoja de calculo',
        'hojas de calculo',
        'planilla',
        'planillas',
        'power query',
        'power pivot',
        'tablas dinamicas',
        'tabla dinamica',
        'spreadsheet',
        'spreadsheets',
      ],
    },
    {
      id: 'powerbi',
      nombre: 'Power BI',
      keywords: [
        'power bi',
        'powerbi',
        'power-bi',
        'power_bi',
        'power.bi',
        'microsoft power bi',
        'bi',
        'dax',
        'tablero de control',
        'tableros de control',
        'dashboard',
        'dashboards',
        'business intelligence',
        'inteligencia de negocios',
        'inteligencia de negocio',
      ],
    },
    {
      id: 'sql',
      nombre: 'SQL Server',
      keywords: [
        'sql',
        'sql server',
        'microsoft sql',
        'tsql',
        't-sql',
        'transact-sql',
        'transact sql',
        'base de datos',
        'bases de datos',
        'stored procedure',
        'stored procedures',
        'procedimiento almacenado',
        'procedimientos almacenados',
        'ssis',
        'ssrs',
        'ssas',
        'pl/sql',
        'pl-sql',
        'plsql',
      ],
    },
    {
      id: 'powerautomate',
      nombre: 'Power Automate',
      keywords: [
        'power automate',
        'powerautomate',
        'power-automate',
        'power apps',
        'powerapps',
        'power-apps',
        'power platform',
        'power-platform',
        'microsoft power platform',
        'flujo de trabajo',
        'flujos de trabajo',
        'automatizacion de procesos',
        'automatizacion de proceso',
        'rpa',
        'robotic process',
      ],
    },
    {
      id: 'analisis',
      nombre: 'Análisis de datos',
      keywords: [
        'analisis de datos',
        'analitica de datos',
        'analitica',
        'data analytics',
        'visualizacion de datos',
        'visualizacion',
        'etl',
        'datamart',
        'data mart',
        'data warehouse',
        'datawarehouse',
        'data-warehouse',
        'indicadores de gestion',
        'indicador de gestion',
        'kpi',
        'kpis',
        'reportes gerenciales',
        'reporte gerencial',
        'business analytics',
      ],
    },
    {
      id: 'ia',
      nombre: 'IA / Machine Learning',
      keywords: [
        'ia',
        'i.a.',
        'i.a',
        'inteligencia artificial',
        'machine learning',
        'machine-learning',
        'aprendizaje automatico',
        'deep learning',
        'deep-learning',
        'aprendizaje profundo',
        'ciencia de datos',
        'data science',
        'redes neuronales',
        'red neuronal',
        'analisis predictivo',
        'modelos predictivos',
        'modelo predictivo',
        'algoritmos de ia',
        'algoritmo de ia',
        'chatbot',
        'chatbots',
        'llm',
        'llms',
        'generative ai',
        'ia generativa',
        'chatgpt',
        'gpt',
        'copilot',
        'openai',
        'prompt engineering',
        'prompting',
      ],
    },
    {
      id: 'bigdata',
      nombre: 'Big Data',
      keywords: [
        'big data',
        'bigdata',
        'big-data',
        'hadoop',
        'spark',
        'data lake',
        'datalake',
        'data-lake',
        'procesamiento de datos masivos',
        'datos masivos',
        'dato masivo',
      ],
    },
    {
      id: 'python',
      nombre: 'Python / Programación',
      keywords: [
        'python',
        'programacion',
        'desarrollo de software',
        'lenguaje de programacion',
        'pandas',
        'django',
        'flask',
        'scripting',
        'rstudio',
        'lenguaje r',
      ],
    },
    {
      id: 'formacion',
      nombre: 'Capacitación / Formación',
      keywords: [
        'capacitacion',
        'capacitaciones',
        'formacion',
        'formaciones',
        'curso',
        'cursos',
        'taller',
        'talleres',
        'entrenamiento',
        'entrenamientos',
        'perfeccionamiento',
        'docencia',
        'capacitar',
        'instructoria',
        'diplomado',
        'diplomados',
        'certificacion',
        'certificaciones',
        'e-learning',
        'elearning',
        'e learning',
        'capacitacion online',
        'capacitacion presencial',
        'instruccion',
        'ensenanza',
      ],
    },
  ],
};

module.exports = { KEYWORDS_DEFAULT };
